
all:
	@echo "targets"
	@echo
	@echo "build - Build the example"
	@echo "clean - tidy up"

build:
	rm -rf build_hex
	mkdir build_hex
	pycc scroll_image.p scroll_image.hex build_hex/

clean:
	rm -rf build_hex